### Dataframe 
---

É um elemento mais importante do Pandas, e são diretamente inspirados pela linguagem R. Podemos pensar no Dataframe como varios objetos da Série juntos, para compartilhar o mesmo indice

In [ ]:
%pip install pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\fic-ti especifico\appdata\roaming\python\python313\site-packages (2.3.2)
Requirement already satisfied: numpy in c:\users\fic-ti especifico\appdata\roaming\python\python313\site-packages (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\fic-ti especifico\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\fic-ti especifico\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\fic-ti especifico\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\fic-ti especifico\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
import numpy as np

dataframe_vazio = pd.DataFrame()

print("Tipo de dado:",type(dataframe_vazio))

Tipo de dado: <class 'pandas.core.frame.DataFrame'>

In [5]:
# Criando DataFrame a partir de dicionarios

dados_dicionario = {
    'Data': ['2020-01-01','2020-02-01','2020-03-01','2020-04-01','2020-05-01'],
    'Temperatura': [29.1,31.2,28.5,28.0,24],
    'Classificação': ['Quente','Muito quente','Quente','Quente','Moderado']
}

print("Tipos de Dados",type(dados_dicionario))

Tipos de Dados <class 'dict'>

In [7]:
dicionario_dataframe = pd.DataFrame(dados_dicionario)

display(dicionario_dataframe)

         Data  Temperatura Classificação
0  2020-01-01         29.1        Quente
1  2020-02-01         31.2  Muito quente
2  2020-03-01         28.5        Quente
3  2020-04-01         28.0        Quente
4  2020-05-01         24.0      Moderado

In [ ]:
# Criando Arquivo CSV

pd.DataFrame.to_csv(dicionario_dataframe, 'arquivo.csv', sep=',', index=False)

In [10]:
# Criar um DataFrame a partir de um CSV

df = pd.read_csv('arquivo.csv')
df

         Data  Temperatura Classificação
0  2020-01-01         29.1        Quente
1  2020-02-01         31.2  Muito quente
2  2020-03-01         28.5        Quente
3  2020-04-01         28.0        Quente
4  2020-05-01         24.0      Moderado

In [14]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\fic-ti especifico\appdata\roaming\python\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\fic-ti especifico\appdata\roaming\python\python313\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
pd.DataFrame.to_excel(dicionario_dataframe, 'arquivo.xlsx', index=False)

In [13]:
excel_arquivo = pd.read_excel('arquivo.xlsx')
display(excel_arquivo)

         Data  Temperatura Classificação
0  2020-01-01         29.1        Quente
1  2020-02-01         31.2  Muito quente
2  2020-03-01         28.5        Quente
3  2020-04-01         28.0        Quente
4  2020-05-01         24.0      Moderado

In [18]:
display(excel_arquivo.columns)
display(excel_arquivo.index)
display(excel_arquivo.dtypes)
display(excel_arquivo.shape)
display(excel_arquivo.head(2))
display(excel_arquivo.tail(2))

Index(['Data', 'Temperatura', 'Classificação'], dtype='object')

RangeIndex(start=0, stop=5, step=1)

Data              object
Temperatura      float64
Classificação     object
dtype: object

(5, 3)

         Data  Temperatura Classificação
0  2020-01-01         29.1        Quente
1  2020-02-01         31.2  Muito quente

         Data  Temperatura Classificação
3  2020-04-01         28.0        Quente
4  2020-05-01         24.0      Moderado

### Desafio 1

In [29]:
desafio1 = {
    'X':[78,85,96,80,86],
    'Y':[84,94,85,83,86],
    'Z':[86,97,96,72,83]
}

dataframe_desafio1 = pd.DataFrame(desafio1)
display(dataframe_desafio1)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  85  96
3  80  83  72
4  86  86  83

### Desafio 2

Dados do Exame

Nome [Ana,Bruno,Camila,Daniel,Fernanda,Gabriel,Helena,Igor,Juliana,Lucas]
pontuação [12.5,9,16.5,None,9,20,14.5,None,8,19]
tentativas [1,3,2,3,2,3,1,1,2,1]
qualificado [sim,não,sim,não,não,sim,sim,não,não,sim]

#### Indices
indice [A,B,C,D,E,F,G,H,I,J]

In [34]:
nomes = ["Ana", "Bruno", "Camila", "Daniel", "Fernanda", "Gabriel", "Helena", "Igor", "Juliana", "Lucas"]
pontuacao = [12.5,9,16.5,None,9,20,14.5,None,8,19]
tentativas = [1,3,2,3,2,3,1,1,2,1]
qualificado = ["sim", "não", "sim", "não", "não", "sim", "sim", "não", "não", "sim"]
indice = ['A','B','C','D','E','F','G','H','I','J']

dicionario_desafio2 = {
    'nome': nomes,
    'pontuação': pontuacao,
    'tentativas': tentativas,
    'qualificado': qualificado
}

dataframe_desafio2 = pd.DataFrame(dicionario_desafio2, index=indice)
display(dataframe_desafio2)

pd.DataFrame.to_excel(dataframe_desafio2,'desafio.xlsx',index=False)

       nome  pontuação  tentativas qualificado
A       Ana       12.5           1         sim
B     Bruno        9.0           3         não
C    Camila       16.5           2         sim
D    Daniel        NaN           3         não
E  Fernanda        9.0           2         não
F   Gabriel       20.0           3         sim
G    Helena       14.5           1         sim
H      Igor        NaN           1         não
I   Juliana        8.0           2         não
J     Lucas       19.0           1         sim